server:
  port: 82

spring:
  application:
    name: assignment

  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 3000MB

  datasource:
    url: jdbc:h2:mem:imdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

    h2:
      console:
        settings:
          web-allow-others: true

#  datasource:
#    url: jdbc:postgresql://localhost:5432/imdb
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect



springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs